package scripts_test

import (
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
)

const firewallDump = `# Generated by iptables-save v1.8.10 (nf_tables) on Sun Sep 13 12:00:00 2026
*filter
:INPUT ACCEPT [10:800]
:FORWARD DROP [42:4096]
:AWGDOCUI - [0:0]
-A INPUT -i awg0 -m comment --comment "VPN #1 [10:800]" -j ACCEPT
-A FORWARD -i awg0 -j ACCEPT
-A FORWARD -o awg0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
COMMIT
# Completed on Sun Sep 13 12:00:00 2026
*nat
:POSTROUTING ACCEPT [55:12345]
-A POSTROUTING -s 10.8.0.0/24 -j MASQUERADE
COMMIT
`

const normalizedFirewallDump = `*filter
:INPUT ACCEPT [0:0]
:FORWARD DROP [0:0]
:AWGDOCUI - [0:0]
-A INPUT -i awg0 -m comment --comment "VPN #1 [10:800]" -j ACCEPT
-A FORWARD -i awg0 -j ACCEPT
-A FORWARD -o awg0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
COMMIT
*nat
:POSTROUTING ACCEPT [0:0]
-A POSTROUTING -s 10.8.0.0/24 -j MASQUERADE
COMMIT
`

// Run the real snapshot script against a read-only fake save command. No host
// firewall privileges or installed iptables tools are required for these tests.
func snapshot(t *testing.T, tool, dump, exitCode string) (string, string, error) {
	t.Helper()
	dir := t.TempDir()
	fixture := filepath.Join(dir, "fixture")
	if err := os.WriteFile(fixture, []byte(dump), 0o600); err != nil {
		t.Fatal(err)
	}
	stub := "#!/bin/sh\n[ \"$#\" -eq 0 ] || exit 98\ncat \"$FIREWALL_FIXTURE\"\nexit \"$FIREWALL_EXIT\"\n"
	if err := os.WriteFile(filepath.Join(dir, tool), []byte(stub), 0o700); err != nil {
		t.Fatal(err)
	}
	output := filepath.Join(dir, "snapshot")
	cmd := exec.Command("sh", "firewall-snapshot.sh", tool, output)
	cmd.Env = append(os.Environ(), "PATH="+dir+string(os.PathListSeparator)+os.Getenv("PATH"),
		"FIREWALL_FIXTURE="+fixture, "FIREWALL_EXIT="+exitCode)
	message, err := cmd.CombinedOutput()
	if err != nil {
		if _, statErr := os.Stat(output); !os.IsNotExist(statErr) {
			t.Fatalf("failed read produced a comparable snapshot: %v", statErr)
		}
		return "", string(message), err
	}
	raw, err := os.ReadFile(output + ".raw")
	if err != nil || string(raw) != dump {
		t.Fatalf("raw diagnostic snapshot was not preserved: %v", err)
	}
	for _, path := range []string{output, output + ".raw"} {
		info, err := os.Stat(path)
		if err != nil {
			t.Fatal(err)
		}
		if info.Mode().Perm() != 0o600 {
			t.Fatalf("snapshot %s mode = %o, want 0600", path, info.Mode().Perm())
		}
	}
	normalized, err := os.ReadFile(output)
	if err != nil {
		t.Fatal(err)
	}
	return string(normalized), string(message), nil
}

func TestFirewallSnapshotIgnoresOnlyVolatileMetadata(t *testing.T) {
	traffic := strings.NewReplacer(
		"12:00:00", "12:02:35",
		":INPUT ACCEPT [10:800]", ":INPUT ACCEPT [200:18000]",
		":FORWARD DROP [42:4096]", ":FORWARD DROP [99:10000]",
		":POSTROUTING ACCEPT [55:12345]", ":POSTROUTING ACCEPT [100:50000]",
	).Replace(firewallDump)
	for _, tool := range []string{"iptables-save", "ip6tables-save"} {
		t.Run(tool, func(t *testing.T) {
			for _, dump := range []string{firewallDump, traffic, strings.Replace(firewallDump, "(nf_tables)", "(legacy)", 1)} {
				got, message, err := snapshot(t, tool, dump, "0")
				if err != nil {
					t.Fatalf("snapshot: %v: %s", err, message)
				}
				if got != normalizedFirewallDump {
					t.Fatalf("unexpected normalized rules:\n%s", got)
				}
			}
		})
	}
}

func TestFirewallSnapshotPreservesActualChanges(t *testing.T) {
	inbound := "-A FORWARD -i awg0 -j ACCEPT\n"
	outbound := "-A FORWARD -o awg0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT\n"
	cases := map[string]string{
		"added rule":      strings.Replace(firewallDump, inbound, inbound+"-A INPUT -p tcp --dport 22 -j ACCEPT\n", 1),
		"deleted rule":    strings.Replace(firewallDump, inbound, "", 1),
		"reordered rules": strings.Replace(firewallDump, inbound+outbound, outbound+inbound, 1),
		"changed policy":  strings.Replace(firewallDump, ":FORWARD DROP", ":FORWARD ACCEPT", 1),
		"changed target":  strings.Replace(firewallDump, "-j MASQUERADE", "-j ACCEPT", 1),
		"changed subnet":  strings.Replace(firewallDump, "10.8.0.0/24", "10.9.0.0/24", 1),
		"changed chain":   strings.Replace(firewallDump, ":AWGDOCUI -", ":OTHER -", 1),
		"literal counter": strings.Replace(firewallDump, "VPN #1 [10:800]", "VPN #1 [11:900]", 1),
		"literal hash":    strings.Replace(firewallDump, "VPN #1", "VPN #2", 1),
		"removed ruleset": "",
	}
	for name, dump := range cases {
		t.Run(name, func(t *testing.T) {
			got, message, err := snapshot(t, "iptables-save", dump, "0")
			if err != nil {
				t.Fatalf("snapshot: %v: %s", err, message)
			}
			if got == normalizedFirewallDump {
				t.Fatal("normalization hid a real firewall change")
			}
		})
	}
}

func TestFirewallSnapshotRejectsFailedRead(t *testing.T) {
	for _, tool := range []string{"iptables-save", "ip6tables-save"} {
		for _, dump := range []string{"", firewallDump} {
			_, message, err := snapshot(t, tool, dump, "4")
			if err == nil || !strings.Contains(message, tool+" could not read firewall rules") {
				t.Fatalf("expected explicit error, got %v: %s", err, message)
			}
		}
	}
}
